sites:
    gme.medicine.uiowa.edu:
        dev: gme-dev.medicine.uiowa.edu
        stage: gme-stage.medicine.uiowa.edu
    www.medicine.uiowa.edu:
        dev: www-dev.medicine.uiowa.edu
        stage: www-stage.medicine.uiowa.edu
    www.medicine.uiowa.edu/internalmedicine:
        dev: www-dev.medicine.uiowa.edu/internalmedicine
        stage: www-stage.medicine.uiowa.edu/internalmedicine
    uihc.org:
        dev: www-dev.uihc.org
        stage: www-stage.uihc.org
    uihc.org/nursingjobs:
        dev: www-dev.uihc.org/nursingjobs
        stage: www-stage.uihc.org/nursingjobs
    uihc.org/transplant:
        dev: www-dev.uihc.org/transplant
        stage: www-stage.uihc.org/transplant
