sites:
    gme.medicine.uiowa.edu:
        dev: gme-dev.medicine.uiowa.edu
        stage: gme-stage.medicine.uiowa.edu
    www.medicine.uiowa.edu:
        dev: www-dev.medicine.uiowa.edu
        stage: www-stage.medicine.uiowa.edu
        internal-prod: www2.medicine.uiowa.edu
    www.medicine.uiowa.edu/internalmedicine:
        dev: www-dev.medicine.uiowa.edu/internalmedicine
        stage: www-stage.medicine.uiowa.edu/internalmedicine
        internal-prod: www2.medicine.uiowa.edu/internalmedicine
    www.medicine.uiowa.edu/neurosurgery:
        dev: www-dev.medicine.uiowa.edu/neurosurgery
        stage: www-stage.medicine.uiowa.edu/neurosurgery
        internal-prod: www2.medicine.uiowa.edu/neurosurgery
    uichildrens.org:
        dev: www-dev.uichildrens.org
        stage: www-stage.uichildrens.org
    uihc.org:
        dev: www-dev.uihc.org
        stage: www-stage.uihc.org
    uihc.org/clinicaltrials:
        dev: www-dev.uihc.org/clinicaltrials
        stage: www-stage.uihc.org/clinicaltrials
    uihc.org/nursingjobs:
        dev: www-dev.uihc.org/nursingjobs
        stage: www-stage.uihc.org/nursingjobs
    uihc.org/transplant:
        dev: www-dev.uihc.org/transplant
        stage: www-stage.uihc.org/transplant
    uihc.org/ucedd:
        dev: www-dev.uihc.org/ucedd
        stage: www-stage.uihc.org/ucedd
