sites:
    www.dentistry.uiowa.edu:
        dev: dentistry.dev.drupal.uiowa.edu
        stage: dentistry.stage.drupal.uiowa.edu
        internal-prod: dentistry.prod.drupal.uiowa.edu
    gme.medicine.uiowa.edu:
        dev: gme-dev.medicine.uiowa.edu
        stage: gme-stage.medicine.uiowa.edu
    icts.uiowa.edu:
        dev: www-dev.icts.uiowa.edu
        stage: www-stage.icts.uiowa.edu
        internal-prod: www.icts.uiowa.edu
    intradent.dentistry.uiowa.edu:
        dev: dentistryintradent.dev.drupal.uiowa.edu
        stage: dentistryintradent.stage.drupal.uiowa.edu
        internal-prod: dentistryintradent.prod.drupal.uiowa.edu
    medicine.uiowa.edu:
        dev: www-dev.medicine.uiowa.edu
        stage: www-stage.medicine.uiowa.edu
        internal-prod: www2.medicine.uiowa.edu
    medicine.uiowa.edu/acb:
        dev: www-dev.medicine.uiowa.edu/acb
        stage: www-stage.medicine.uiowa.edu/acb
        internal-prod: www2.medicine.uiowa.edu/acb
    medicine.uiowa.edu/biochemistry:
        dev: www-dev.medicine.uiowa.edu/biochemistry
        stage: www-stage.medicine.uiowa.edu/biochemistry
        internal-prod: www2.medicine.uiowa.edu/biochemistry
    medicine.uiowa.edu/biomed:
        dev: www-dev.medicine.uiowa.edu/biomed
        stage: www-stage.medicine.uiowa.edu/biomed
        internal-prod: www2.medicine.uiowa.edu/biomed
    medicine.uiowa.edu/dermatology:
        dev: www-dev.medicine.uiowa.edu/dermatology
        stage: www-stage.medicine.uiowa.edu/dermatology
        internal-prod: www2.medicine.uiowa.edu/dermatology
    medicine.uiowa.edu/emergencymedicine:
        dev: www-dev.medicine.uiowa.edu/emergencymedicine
        stage: www-stage.medicine.uiowa.edu/emergencymedicine
        internal-prod: www2.medicine.uiowa.edu/emergencymedicine
    medicine.uiowa.edu/eye:
        dev: www-dev.medicine.uiowa.edu/eye
        stage: www-stage.medicine.uiowa.edu/eye
        internal-prod: www2.medicine.uiowa.edu/eye
    medicine.uiowa.edu/familymedicine:
        dev: www-dev.medicine.uiowa.edu/familymedicine
        stage: www-stage.medicine.uiowa.edu/familymedicine
        internal-prod: www2.medicine.uiowa.edu/familymedicine
    medicine.uiowa.edu/immunology:
        dev: www-dev.medicine.uiowa.edu/immunology
        stage: www-stage.medicine.uiowa.edu/immunology
        internal-prod: www2.medicine.uiowa.edu/immunology
    medicine.uiowa.edu/internalmedicine:
        dev: www-dev.medicine.uiowa.edu/internalmedicine
        stage: www-stage.medicine.uiowa.edu/internalmedicine
        internal-prod: www2.medicine.uiowa.edu/internalmedicine
    medicine.uiowa.edu/mcb:
        dev: www-dev.medicine.uiowa.edu/mcb
        stage: www-stage.medicine.uiowa.edu/mcb
        internal-prod: www2.medicine.uiowa.edu/mcb
    medicine.uiowa.edu/microbiology:
        dev: www-dev.medicine.uiowa.edu/microbiology
        stage: www-stage.medicine.uiowa.edu/microbiology
        internal-prod: www2.medicine.uiowa.edu/microbiology
    medicine.uiowa.edu/neurology:
        dev: www-dev.medicine.uiowa.edu/neurology
        stage: www-stage.medicine.uiowa.edu/neurology
        internal-prod: www2.medicine.uiowa.edu/neurology
    medicine.uiowa.edu/neurosurgery:
        dev: www-dev.medicine.uiowa.edu/neurosurgery
        stage: www-stage.medicine.uiowa.edu/neurosurgery
        internal-prod: www2.medicine.uiowa.edu/neurosurgery
    medicine.uiowa.edu/obgyn:
        dev: www-dev.medicine.uiowa.edu/obgyn
        stage: www-stage.medicine.uiowa.edu/obgyn
        internal-prod: www2.medicine.uiowa.edu/obgyn
    medicine.uiowa.edu/orthopedics:
        dev: www-dev.medicine.uiowa.edu/orthopedics
        stage: www-stage.medicine.uiowa.edu/orthopedics
        internal-prod: www2.medicine.uiowa.edu/orthopedics
    medicine.uiowa.edu/oto:
        dev: www-dev.medicine.uiowa.edu/oto
        stage: www-stage.medicine.uiowa.edu/oto
        internal-prod: www2.medicine.uiowa.edu/oto
    medicine.uiowa.edu/pathology:
        dev: www-dev.medicine.uiowa.edu/pathology
        stage: www-stage.medicine.uiowa.edu/pathology
        internal-prod: www2.medicine.uiowa.edu/pathology
    medicine.uiowa.edu/pediatrics:
        dev: www-dev.medicine.uiowa.edu/pediatrics
        stage: www-stage.medicine.uiowa.edu/pediatrics
        internal-prod: www2.medicine.uiowa.edu/pediatrics
    medicine.uiowa.edu/pharmacology:
        dev: www-dev.medicine.uiowa.edu/pharmacology
        stage: www-stage.medicine.uiowa.edu/pharmacology
        internal-prod: www2.medicine.uiowa.edu/pharmacology
    medicine.uiowa.edu/physiology:
        dev: www-dev.medicine.uiowa.edu/physiology
        stage: www-stage.medicine.uiowa.edu/physiology
        internal-prod: www2.medicine.uiowa.edu/physiology
    medicine.uiowa.edu/psychiatry:
        dev: www-dev.medicine.uiowa.edu/psychiatry
        stage: www-stage.medicine.uiowa.edu/psychiatry
        internal-prod: www2.medicine.uiowa.edu/psychiatry
    medicine.uiowa.edu/pt:
        dev: www-dev.medicine.uiowa.edu/pt
        stage: www-stage.medicine.uiowa.edu/pt
        internal-prod: www2.medicine.uiowa.edu/pt
    medicine.uiowa.edu/radiationoncology:
        dev: www-dev.medicine.uiowa.edu/radiationoncology
        stage: www-stage.medicine.uiowa.edu/radiationoncology
        internal-prod: www2.medicine.uiowa.edu/radiationoncology
    medicine.uiowa.edu/radiology:
        dev: www-dev.medicine.uiowa.edu/radiology
        stage: www-stage.medicine.uiowa.edu/radiology
        internal-prod: www2.medicine.uiowa.edu/radiology
    medicine.uiowa.edu/surgery:
        dev: www-dev.medicine.uiowa.edu/surgery
        stage: www-stage.medicine.uiowa.edu/surgery
        internal-prod: www2.medicine.uiowa.edu/surgery
    medicine.uiowa.edu/urology:
        dev: www-dev.medicine.uiowa.edu/urology
        stage: www-stage.medicine.uiowa.edu/urology
        internal-prod: www2.medicine.uiowa.edu/urology
    medicine.uiowa.edu/sercc:
        dev: www-dev.medicine.uiowa.edu/sercc
        stage: www-stage.medicine.uiowa.edu/sercc
        internal-prod: www2.medicine.uiowa.edu/sercc
    signage.uihealthcare.org:
        dev: signage-dev.uihealthcare.org
        stage: signage-stage.uihealthcare.org
    uichildrens.org:
        dev: www-dev.uichildrens.org
        stage: www-stage.uichildrens.org
    uihc.org:
        dev: www-dev.uihc.org
        stage: www-stage.uihc.org
    uihc.org/clinicaltrials:
        dev: www-dev.uihc.org/clinicaltrials
        stage: www-stage.uihc.org/clinicaltrials
    uihc.org/nursingjobs:
        dev: www-dev.uihc.org/nursingjobs
        stage: www-stage.uihc.org/nursingjobs
    uihc.org/transplant:
        dev: www-dev.uihc.org/transplant
        stage: www-stage.uihc.org/transplant
    uihc.org/ucedd:
        dev: www-dev.uihc.org/ucedd
        stage: www-stage.uihc.org/ucedd
    uihealthcare.org:
        dev: www-dev.uihealthcare.org
        stage: www-stage.uihealthcare.org
    signage.uiowa.edu:
        dev: signage-dev.uiowa.edu
        stage: signage-stage.uiowa.edu
    admissions.uiowa.edu:
        dev: admissions.dev.drupal.uiowa.edu
        stage: admissions.stage.drupal.uiowa.edu
        internal-prod: admissions.uiowa.edu
    amcs.uiowa.edu:
        dev: amcs.dev.drupal.uiowa.edu
        stage: amcs.stage.drupal.uiowa.edu
        internal-prod: www.amcs.uiowa.edu
    book.grad.uiowa.edu:
        dev: book.dev.drupal.uiowa.edu
        stage: book.stage.drupal.uiowa.edu
        internal-prod: book.grad.uiowa.edu
    cogscilang.grad.uiowa.edu:
        dev: cogscilang.dev.drupal.uiowa.edu
        stage: cogscilang.stage.drupal.uiowa.edu
        internal-prod: cogscilang.grad.uiowa.edu
    forms.grad.uiowa.edu:
        dev: forms.dev.drupal.uiowa.edu
        stage: forms.stage.drupal.uiowa.edu
        internal-prod: forms.grad.uiowa.edu
    genetics.grad.uiowa.edu:
        dev: igpgenetics.dev.drupal.uiowa.edu
        stage: igpgenetics.stage.drupal.uiowa.edu
        internal-prod: genetics.grad.uiowa.edu
    grad.admissions.uiowa.edu:
        dev: grad-admissions.dev.drupal.uiowa.edu
        stage: grad-admissions.stage.drupal.uiowa.edu
        internal-prod: grad.admissions.uiowa.edu
    gss.grad.uiowa.edu:
        dev: gss.dev.drupal.uiowa.edu
        stage: gss.stage.drupal.uiowa.edu
        internal-prod: gss.grad.uiowa.edu
    iowasuperfund.uiowa.edu:
        dev: iowasuperfund.dev.drupal.uiowa.edu
        stage: iowasuperfund.stage.drupal.uiowa.edu
        internal-prod: iowasuperfund.uiowa.edu
    iwp.grad.uiowa.edu:
        dev: iwpnom.dev.drupal.uiowa.edu
        stage: iwpnom.stage.drupal.uiowa.edu
        internal-prod: iwp.grad.uiowa.edu
    iwp.uiowa.edu:
        dev: iwp.dev.drupal.uiowa.edu
        stage: iwp.stage.drupal.uiowa.edu
        internal-prod: iwp.uiowa.edu
    iwp.uiowa.edu/whitmanweb:
        dev: iwpww.dev.drupal.uiowa.edu
        stage: iwpww.stage.drupal.uiowa.edu
        internal-prod: iwp.uiowa.edu/whitmanweb
    iwp.uiowa.edu/publishing-gallery:
        dev: iwppg.dev.drupal.uiowa.edu
        stage: iwppg.stage.drupal.uiowa.edu
        internal-prod: iwp.uiowa.edu/publishing-gallery
    iwp.uiowa.edu/shse:
        dev: iwpshse.dev.drupal.uiowa.edu
        stage: iwpshse.stage.drupal.uiowa.edu
        internal-prod: iwp.uiowa.edu/shse
    iwp.uiowa.edu/silkroutes:
        dev: iwpsr.dev.drupal.uiowa.edu
        stage: iwpsr.stage.drupal.uiowa.edu
        internal-prod: iwp.uiowa.edu/silkroutes
    neuroscience.grad.uiowa.edu:
        dev: igpneuroscience.dev.drupal.uiowa.edu
        stage: igpneuroscience.stage.drupal.uiowa.edu
        internal-prod: neuroscience.grad.uiowa.edu
    placement.grad.uiowa.edu:
        dev: gcplacement.dev.drupal.uiowa.edu
        stage: gcplacement.stage.drupal.uiowa.edu
        internal-prod: placement.grad.uiowa.edu
    placement2.grad.uiowa.edu:
        dev: gcplacement2.dev.drupal.uiowa.edu
        stage: gcplacement2.stage.drupal.uiowa.edu
    rio.urban.uiowa.edu:
        dev: rio.dev.drupal.uiowa.edu
        stage: rio.stage.drupal.uiowa.edu
        internal-prod: rio.urban.uiowa.edu
    slis.uiowa.edu:
        dev: slis.dev.drupal.uiowa.edu
        stage: slis.stage.drupal.uiowa.edu
        internal-prod: www.slis.uiowa.edu
    toxicology.grad.uiowa.edu:
        dev: toxicology.dev.drupal.uiowa.edu
        stage: toxicology.stage.drupal.uiowa.edu
        internal-prod: toxicology.grad.uiowa.edu
    uipda.grad.uiowa.edu:
        dev: uipda.dev.drupal.uiowa.edu
        stage: uipda.stage.drupal.uiowa.edu
        internal-prod: uipda.grad.uiowa.edu
    uipress.uiowa.edu:
        dev: uipress.dev.drupal.uiowa.edu
        stage: uipress.stage.drupal.uiowa.edu
        internal-prod: www.uipress.uiowa.edu
    urban.uiowa.edu:
        dev: urban.dev.drupal.uiowa.edu
        stage: urban.stage.drupal.uiowa.edu
        internal-prod: www.urban.uiowa.edu
    urban2.uiowa.edu:
        dev: urban2.dev.drupal.uiowa.edu
        stage: urban2.stage.drupal.uiowa.edu
    writinguniversity.org:
        dev: vwu.dev.drupal.uiowa.edu
        stage: vwu.stage.drupal.uiowa.edu
        internal-prod: www.writinguniversity.org
    www.grad.uiowa.edu:
        dev: gc.dev.drupal.uiowa.edu
        stage: gc.stage.drupal.uiowa.edu
        internal-prod: www.grad.uiowa.edu
